import io
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def export_to_docx(sections: list[dict], project_name: str) -> bytes:
    from docx import Document
    from docx.shared import Inches, Pt

    doc = Document()

    style = doc.styles["Title"]
    style.font.size = Pt(24)
    doc.add_heading(f"RFP Response: {project_name}", level=0)

    doc.add_paragraph("Generated by RFP Copilot Platform")
    doc.add_paragraph("")

    doc.add_heading("Table of Contents", level=1)
    for section in sections:
        doc.add_paragraph(
            f"{section.get('tab_index', 0) + 1}. {section.get('title', 'Untitled')}",
            style="List Number",
        )
    doc.add_page_break()

    for section in sections:
        doc.add_heading(section.get("title", "Untitled"), level=1)

        confidence = section.get("confidence_score")
        if confidence is not None:
            doc.add_paragraph(f"Confidence Score: {confidence:.0f}%")

        content = section.get("content", "")
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("## "):
                doc.add_heading(stripped[3:], level=2)
            elif stripped.startswith("### "):
                doc.add_heading(stripped[4:], level=3)
            elif stripped.startswith("| ") and " | " in stripped:
                doc.add_paragraph(stripped, style="List Bullet")
            elif stripped.startswith("- "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped.startswith("* "):
                doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped:
                doc.add_paragraph(stripped)

        doc.add_page_break()

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


def export_to_pdf(sections: list[dict], project_name: str) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"], fontSize=24, spaceAfter=20
    )
    story.append(Paragraph(f"RFP Response: {project_name}", title_style))
    story.append(Paragraph("Generated by RFP Copilot Platform", styles["Normal"]))
    story.append(Spacer(1, 30))

    for section in sections:
        story.append(Paragraph(section.get("title", "Untitled"), styles["Heading1"]))

        confidence = section.get("confidence_score")
        if confidence is not None:
            story.append(
                Paragraph(f"Confidence Score: {confidence:.0f}%", styles["Italic"])
            )
        story.append(Spacer(1, 10))

        content = section.get("content", "")
        for line in content.split("\n"):
            stripped = line.strip()
            if stripped.startswith("## "):
                story.append(Paragraph(stripped[3:], styles["Heading2"]))
            elif stripped.startswith("### "):
                story.append(Paragraph(stripped[4:], styles["Heading3"]))
            elif stripped.startswith("- ") or stripped.startswith("* "):
                bullet_text = stripped[2:]
                story.append(Paragraph(f"\u2022 {bullet_text}", styles["Normal"]))
            elif stripped:
                story.append(Paragraph(stripped, styles["Normal"]))

        story.append(Spacer(1, 20))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
